# fly.toml app configuration file generated for snet on 2025-06-06T16:18:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snet'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile.frontend'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build.args]
NEXT_PUBLIC_FLY_APP_NAME = "${NEXT_PUBLIC_FLY_APP_NAME}"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
